### ISSUE TITLE
Issue launching NEO GEO games (cross hatch test)

### ISSUE THREAD

**Issue by felleg** [pocomane/MiSTer_Batch_Control#30]
Info about my `mbc` setup:

```
Build timestamp: 2022-09-10/16:27:39+00:00
Build commit: 4dcd07e9ba4f18edcf916642d23a06bfe66a702d
```

When I try launching a NEO GEO rom using a command similar to this one:
```
mbc load_rom NEOGEO /media/fat/games/NEOGEO/1\ World\ A-Z/Blazing\ Star\ \(blazstar\).neo
```

I get a cross hatch test:
![image](https://user-images.githubusercontent.com/7781739/201774992-9e0d38f6-b0f7-44f3-979c-afcd33c8a974.png)

This neo geo game works when I try to load it directly, or via a mgl, which contains the following:
```
<mistergamedescription>
	<rbf>_Console/NeoGeo</rbf>
	<file delay="1" type="f" index="1" path="../../../../media/fat/games/NeoGeo/1 World A-Z/Blazing Star (blazstar).neo"/>
</mistergamedescription>
```

Interesting note, when I try to launch a Neo Geo game from mbc while another Neo Geo game is already playing, I get garbled graphics of the already running game. It seems the BIOS is loaded incorrectly. For example, in this image, we see what happens after trying to load Metal Slug 1 (via mbc) while Blazing Star is running (from a manual launch via UI):

![image](https://user-images.githubusercontent.com/7781739/201775605-09908fed-2fb8-4a20-a8de-6aee0bfd57a4.png)
![image](https://user-images.githubusercontent.com/7781739/201775623-5d61676b-c6d9-4423-a0b6-c42b38928d5e.png)
(We see garbled graphics from Blazing Star)

I have attempted to use `MBC_CUSTOM_MODE`, but I get the same result:
```
MBC_CUSTOM_MODE=f1 mbc load_rom NEOGEO /media/fat/games/NEOGEO/1\ World\ A-Z/Metal\ Slug\ -\ Super\ Vehicle-001\ \(mslug\).neo
```

**Comment by pocomane** [comment]
Sorry, I missed this issue when it was open. Effectively there seems to be a bug when running a rom in the default path but with a different capitalization. I mean, on my machine:

```
mbc load_rom NEOGEO /media/fat/games/NEOGEO/Blazing\ Star\ \(blazstar\).neo
```

give issues similar to the reported one, while 


```
mbc load_rom NEOGEO /media/fat/games/NeoGeo/Blazing\ Star\ \(blazstar\).neo
```

correctly works [1]. Can you confirm that the latter works also for you? Just to be sure that there is nothing else wrong; I will try to fix this for any capitalization in the next days in any case.

Thanks for the report!

[1] note "NeoGeo" in the path instead of "NEOGEO"; If you use "mbc mgl_gen" command you can see that the generated path is wrong in the first case.

**Comment by felleg** [comment]
Yup, I confirm that this works for me:

```
mbc load_rom NEOGEO /media/fat/games/NeoGeo/1\ World\ A-Z/Blazing\ Star\ \(blazstar\).neo
```

Strange, I never changed the capitalization for my `NEOGEO` folder. It has always been capitalized as far as I can tell.

Looking forward to the incominf fix, thanks for your help! :)

**Comment by felleg** [comment]
The new fix works for me! Cheers, closing this issue.
